spring:
  profiles:
    active: local
  application:
    name: tick

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      minimum-idle: 20
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

management.metrics:
  export:
    statsd:
      enabled: true
      flavor: telegraf
      polling-frequency: 5s
  tags:
    application: ${spring.application.name}
    active: ${spring.profiles.active}
